package com.model.pojo;
// Generated Oct 8, 2022 10:06:48 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DataAnggota generated by hbm2java
 */
public class DataAnggota  implements java.io.Serializable {


     private Integer idAnggota;
     private MultiuserLogin multiuserLogin;
     private int nim;
     private String namaAnggota;
     private String kelas;
     private String tempatLahir;
     private Date tanggalLahir;

    public DataAnggota() {
    }

    public DataAnggota(MultiuserLogin multiuserLogin, int nim, String namaAnggota, String kelas, String tempatLahir, Date tanggalLahir) {
       this.multiuserLogin = multiuserLogin;
       this.nim = nim;
       this.namaAnggota = namaAnggota;
       this.kelas = kelas;
       this.tempatLahir = tempatLahir;
       this.tanggalLahir = tanggalLahir;
    }
   
    public Integer getIdAnggota() {
        return this.idAnggota;
    }
    
    public void setIdAnggota(Integer idAnggota) {
        this.idAnggota = idAnggota;
    }
    public MultiuserLogin getMultiuserLogin() {
        return this.multiuserLogin;
    }
    
    public void setMultiuserLogin(MultiuserLogin multiuserLogin) {
        this.multiuserLogin = multiuserLogin;
    }
    public int getNim() {
        return this.nim;
    }
    
    public void setNim(int nim) {
        this.nim = nim;
    }
    public String getNamaAnggota() {
        return this.namaAnggota;
    }
    
    public void setNamaAnggota(String namaAnggota) {
        this.namaAnggota = namaAnggota;
    }
    public String getKelas() {
        return this.kelas;
    }
    
    public void setKelas(String kelas) {
        this.kelas = kelas;
    }
    public String getTempatLahir() {
        return this.tempatLahir;
    }
    
    public void setTempatLahir(String tempatLahir) {
        this.tempatLahir = tempatLahir;
    }
    public Date getTanggalLahir() {
        return this.tanggalLahir;
    }
    
    public void setTanggalLahir(Date tanggalLahir) {
        this.tanggalLahir = tanggalLahir;
    }




}


