package com.model.pojo;
// Generated Oct 8, 2022 10:06:48 PM by Hibernate Tools 4.3.1



/**
 * DataPetugas generated by hbm2java
 */
public class DataPetugas  implements java.io.Serializable {


     private Integer idPetugas;
     private MultiuserLogin multiuserLogin;
     private String namaPetugas;
     private String alamat;
     private String noTelp;

    public DataPetugas() {
    }

    public DataPetugas(MultiuserLogin multiuserLogin, String namaPetugas, String alamat, String noTelp) {
       this.multiuserLogin = multiuserLogin;
       this.namaPetugas = namaPetugas;
       this.alamat = alamat;
       this.noTelp = noTelp;
    }
   
    public Integer getIdPetugas() {
        return this.idPetugas;
    }
    
    public void setIdPetugas(Integer idPetugas) {
        this.idPetugas = idPetugas;
    }
    public MultiuserLogin getMultiuserLogin() {
        return this.multiuserLogin;
    }
    
    public void setMultiuserLogin(MultiuserLogin multiuserLogin) {
        this.multiuserLogin = multiuserLogin;
    }
    public String getNamaPetugas() {
        return this.namaPetugas;
    }
    
    public void setNamaPetugas(String namaPetugas) {
        this.namaPetugas = namaPetugas;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public String getNoTelp() {
        return this.noTelp;
    }
    
    public void setNoTelp(String noTelp) {
        this.noTelp = noTelp;
    }




}


