package com.model.pojo;
// Generated Oct 8, 2022 10:06:48 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MultiuserLogin generated by hbm2java
 */
public class MultiuserLogin  implements java.io.Serializable {


     private String username;
     private String password;
     private String loginType;
     private Set<DataAnggota> dataAnggotas = new HashSet<DataAnggota>(0);
     private Set<DataPetugas> dataPetugases = new HashSet<DataPetugas>(0);

    public MultiuserLogin() {
    }

	
    public MultiuserLogin(String username, String password, String loginType) {
        this.username = username;
        this.password = password;
        this.loginType = loginType;
    }
    public MultiuserLogin(String username, String password, String loginType, Set<DataAnggota> dataAnggotas, Set<DataPetugas> dataPetugases) {
       this.username = username;
       this.password = password;
       this.loginType = loginType;
       this.dataAnggotas = dataAnggotas;
       this.dataPetugases = dataPetugases;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getLoginType() {
        return this.loginType;
    }
    
    public void setLoginType(String loginType) {
        this.loginType = loginType;
    }
    public Set<DataAnggota> getDataAnggotas() {
        return this.dataAnggotas;
    }
    
    public void setDataAnggotas(Set<DataAnggota> dataAnggotas) {
        this.dataAnggotas = dataAnggotas;
    }
    public Set<DataPetugas> getDataPetugases() {
        return this.dataPetugases;
    }
    
    public void setDataPetugases(Set<DataPetugas> dataPetugases) {
        this.dataPetugases = dataPetugases;
    }




}


