package com.model.pojo;
// Generated Oct 8, 2022 10:06:48 PM by Hibernate Tools 4.3.1



/**
 * Siswa generated by hbm2java
 */
public class Siswa  implements java.io.Serializable {


     private int idSiswa;
     private int idUjian;

    public Siswa() {
    }

    public Siswa(int idSiswa, int idUjian) {
       this.idSiswa = idSiswa;
       this.idUjian = idUjian;
    }
   
    public int getIdSiswa() {
        return this.idSiswa;
    }
    
    public void setIdSiswa(int idSiswa) {
        this.idSiswa = idSiswa;
    }
    public int getIdUjian() {
        return this.idUjian;
    }
    
    public void setIdUjian(int idUjian) {
        this.idUjian = idUjian;
    }




}


